In [70]:
import pandas as pd
import numpy as np

In [71]:
df = pd.read_csv('dalvi - Sheet1(1).csv')

In [72]:
df.head()

Date                          Target/Issuer    ROCE        FCF  \
0  06/20/2017  MPIL Corporation Limited (BSE:500450) -3.9020  -5.229323   
1  06/20/2017     Redex Protech Limited (BSE:523650)  1.8721  -0.368857   
2  06/20/2017  MPIL Corporation Limited (BSE:500450) -3.9020  -5.229323   
3  06/19/2017  Simplex Castings Limited (BSE:513472)  6.2878  56.868500   
4  06/16/2017  Mehta Securities Limited (BSE:511738)  0.0000  14.293333   

        Growth  Debt-to-equity  Quick Ratio  Asset Ratio  Market-to-book  \
0     7.800000        0.000000     0.000000     0.390321        17.79850   
1     3.135907        0.028672     5.253887     0.450349        47.74941   
2     7.800000        0.000000    21.179460     0.390321        17.79850   
3  1953.099667        0.933444     0.404493     0.733670       165.05617   
4    -2.569333        0.214137     0.009413     0.024400         4.65643   

        size  age  
0  109.17121   58  
1   41.67113   26  
2  109.17121   58  
3  897.03158   47  
4   33.98340   23

In [73]:
df.describe()

ROCE           FCF         Growth  Debt-to-equity  Quick Ratio  \
count  304.000000    304.000000     304.000000      304.000000   304.000000   
mean     3.745882    210.662232    9609.461591        1.233178    14.556464   
std      9.200016   1924.872306   33913.847768        4.462107    57.325768   
min    -30.749100 -15833.366670      -2.569333       -8.591403     0.000000   
25%      0.000000    -18.190931      28.200000        0.000195     0.442122   
50%      1.379100      0.000000     398.768490        0.246677     0.857668   
75%      7.812550     30.984120    3585.174584        0.991495     3.000393   
max     55.379600  17185.091670  360607.019300       36.819665   803.523587   

       Asset Ratio  Market-to-book          size         age  
count   304.000000      304.000000  3.040000e+02  304.000000  
mean      0.381076       31.200021  2.389453e+04   34.618421  
std       0.609196       48.323324  1.528141e+05   21.958687  
min       0.000000        0.000000  0.000000e+00    0.000000  
25%       0.010816        0.000000  1.072783e+02   25.000000  
50%       0.183424       11.901590  3.206986e+02   31.000000  
75%       0.577517       40.513015  3.443115e+03   36.000000  
max       5.070953      278.299670  2.493980e+06  139.000000

In [74]:
df.columns

Index(['Date', 'Target/Issuer', 'ROCE', 'FCF', 'Growth', 'Debt-to-equity',
       'Quick Ratio', 'Asset Ratio', 'Market-to-book', 'size', 'age'],
      dtype='object')

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 11 columns):
Date              304 non-null object
Target/Issuer     304 non-null object
ROCE              304 non-null float64
FCF               304 non-null float64
Growth            304 non-null float64
Debt-to-equity    304 non-null float64
Quick Ratio       304 non-null float64
Asset Ratio       304 non-null float64
Market-to-book    304 non-null float64
size              304 non-null float64
age               304 non-null int64
dtypes: float64(8), int64(1), object(2)
memory usage: 26.2+ KB


In [76]:
df['ROCE'] = df['ROCE'].astype(float)
df['ROCE'] = df['ROCE'].replace('nan', 0)

In [77]:
df.Growth.unique()

array([ 7.80000000e+00,  3.13590667e+00,  1.95309967e+03, -2.56933333e+00,
        7.03128967e+03,  1.76731000e+01,  8.62708967e+01,  1.87815333e+02,
        3.98835350e+03,  3.16143333e+03,  4.23829400e+01,  3.96629770e+02,
        1.57147000e+00,  1.11445270e+03,  6.24955333e+04,  2.14596200e+01,
        3.26174400e+01,  3.28006000e+02,  1.42150985e+04,  3.06792397e+04,
        3.54497113e+02,  2.67488528e+03,  5.78912067e+01,  1.03644667e+00,
        1.82837000e+04,  3.68873667e+04,  2.18370897e+02,  2.35440000e+04,
        1.45307080e+02,  1.94277333e+04,  4.45985399e+03,  4.12400533e+01,
        6.95532933e+01,  6.09082000e+03,  2.31449000e+00,  7.88145667e+00,
        1.00410500e+01,  6.07737893e+02,  7.66710000e-01,  2.20060535e+03,
        6.11466667e+00,  5.96947567e+01,  1.23333333e+00,  1.36830000e+02,
        2.23799067e+05,  3.98768490e+02,  3.07975506e+04,  6.79111000e+02,
        8.00000000e+00,  3.56400533e+01,  1.05454327e+04,  1.42922667e+02,
        3.67951367e+02,  

In [78]:
df.columns

Index(['Date', 'Target/Issuer', 'ROCE', 'FCF', 'Growth', 'Debt-to-equity',
       'Quick Ratio', 'Asset Ratio', 'Market-to-book', 'size', 'age'],
      dtype='object')

In [79]:
df['Growth'].value_counts().head()

414.500483    9
10.041050     6
194.097667    6
32.617440     5
0.000000      5
Name: Growth, dtype: int64

In [80]:
target = df['Growth']
df = df[['ROCE', 'FCF', 'Debt-to-equity',
       'Quick Ratio', 'Asset Ratio', 'Market-to-book', 'size', 'age']]

In [81]:
data = df.values
data

array([[-3.90200000e+00, -5.22932333e+00,  0.00000000e+00, ...,
         1.77985000e+01,  1.09171210e+02,  5.80000000e+01],
       [ 1.87210000e+00, -3.68856667e-01,  2.86722279e-02, ...,
         4.77494100e+01,  4.16711300e+01,  2.60000000e+01],
       [-3.90200000e+00, -5.22932333e+00,  0.00000000e+00, ...,
         1.77985000e+01,  1.09171210e+02,  5.80000000e+01],
       ...,
       [-1.58120000e+00, -8.95754767e+01,  0.00000000e+00, ...,
         2.22958700e+02,  1.54634548e+04,  3.40000000e+01],
       [ 5.39600000e-01, -3.63501600e+01,  0.00000000e+00, ...,
         2.07095300e+01,  2.92150900e+01,  3.60000000e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  7.65000000e+00,  2.50000000e+01]])

In [82]:
target = target.values
target

array([ 7.80000000e+00,  3.13590667e+00,  7.80000000e+00,  1.95309967e+03,
       -2.56933333e+00,  7.03128967e+03,  1.76731000e+01,  8.62708967e+01,
        1.87815333e+02,  3.98835350e+03,  3.16143333e+03,  4.23829400e+01,
        4.23829400e+01,  3.96629770e+02,  3.96629770e+02,  1.57147000e+00,
        1.11445270e+03,  6.24955333e+04,  2.14596200e+01,  3.26174400e+01,
        3.28006000e+02,  3.28006000e+02,  1.42150985e+04,  3.06792397e+04,
        3.54497113e+02,  2.67488528e+03,  5.78912067e+01,  1.03644667e+00,
        3.54497113e+02,  1.82837000e+04,  3.68873667e+04,  2.18370897e+02,
        2.35440000e+04,  1.45307080e+02,  1.94277333e+04,  4.45985399e+03,
        4.12400533e+01,  6.95532933e+01,  6.09082000e+03,  2.31449000e+00,
        2.31449000e+00,  7.88145667e+00,  1.00410500e+01,  6.07737893e+02,
        7.66710000e-01,  2.20060535e+03,  6.11466667e+00,  5.96947567e+01,
        5.96947567e+01,  1.23333333e+00,  1.36830000e+02,  2.23799067e+05,
        3.26174400e+01,  

In [83]:
features = df.columns.values
features

array(['ROCE', 'FCF', 'Debt-to-equity', 'Quick Ratio', 'Asset Ratio',
       'Market-to-book', 'size', 'age'], dtype=object)

In [108]:
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import cross_val_score, ShuffleSplit
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import roc_auc_score

  
scaler = StandardScaler()
X = scaler.fit_transform(data)
Y = target
names = features
l = []
for _ in range(10):
    rf = RandomForestRegressor(n_estimators=20, max_depth=4)
    rf.fit(X,Y)
    scores = []
    for i in range(X.shape[1]):
        score = cross_val_score(rf, X[:, i:i+1], Y, scoring="r2", cv=ShuffleSplit(len(X), 3, .3))
        scores.append((round(np.mean(score), 3), names[i]))
    #print(i)
    #l += scores
    #print('l ' + str(l) + '\n\nscores ' + str(scores))
    #avg += score
print(sorted(scores, reverse=True))
#scores

[(0.411, 'FCF'), (0.369, 'Market-to-book'), (0.163, 'size'), (0.137, 'ROCE'), (0.118, 'Quick Ratio'), (0.039, 'age'), (-0.228, 'Asset Ratio'), (-0.621, 'Debt-to-equity')]


In [32]:
for i in range(10):
    lasso = Lasso(alpha=.3)
    lasso.fit(X, Y)

    scores = []
    for i in range(X.shape[1]):
         score = cross_val_score(rf, X[:, i:i+1], Y, scoring="r2",
                                  cv=ShuffleSplit(len(X), 3, .3))
         scores.append((round(np.mean(score), 3), names[i]))
print(sorted(scores, reverse=True))

[(0.46, 'FCF'), (0.186, 'size'), (0.182, 'ROCE'), (0.11, 'Market-to-book'), (-0.06, 'Asset Ratio'), (-0.074, 'age'), (-0.359, 'Quick Ratio'), (-0.427, 'Debt-to-equity')]


In [31]:
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import cross_val_score, ShuffleSplit
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import roc_auc_score

  
scaler = StandardScaler()
X = scaler.fit_transform(data)
Y = target
names = features
 
for i in range(10):
    rf = RandomForestRegressor(n_estimators=20, max_depth=4)
    rf.fit(X,Y)
    scores = []
    for i in range(X.shape[1]):
         score = cross_val_score(rf, X[:, i:i+1], Y, scoring="r2",
                                  cv=ShuffleSplit(len(X), 3, .3))
         scores.append((round(np.mean(score), 3), names[i]))
    #avg += score
print(sorted(scores, reverse=True))

[(0.098, 'FCF'), (-0.084, 'size'), (-0.112, 'Debt-to-equity'), (-0.168, 'Market-to-book'), (-0.183, 'ROCE'), (-0.185, 'Quick Ratio'), (-2.263, 'Asset Ratio'), (-4.489, 'age')]


In [62]:
scores[0][0]

-0.087